// react-dashboard/src/components/GCodeUpload.tsx
import { useState } from 'react';

interface Machine {
  id: number;
  status: string;
  name: string;
}

interface GCodeUploadProps {
  machines: Machine[];

  onUpload: (machineId: string, file: File) => Promise<void>;
}

export default function GCodeUpload({ machines, onUpload }: GCodeUploadProps) {
  const [selectedMachine, setSelectedMachine] = useState<string>('');
  const [file, setFile] = useState<File | null>(null);
  const [uploading, setUploading] = useState<boolean>(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedMachine || !file) {
      alert('Error: Peak the machine and G-code file!');
      return;
    }

    try {
      setUploading(true);
      await onUpload(selectedMachine, file);
      alert(`${file.name} has successfully uploaded to the machine №${selectedMachine}. The machine is working.`);
      setFile(null);
      setSelectedMachine('');
    } catch (err) {
      alert('Invalid file uploading.');
    } finally {
      setUploading(false);
    }
  };

  return (
    <div className="mx-auto bg-[#111c44] border border-slate-800 p-6 rounded-2xl space-y-6 shadow-xl">
      <div>
        <h2 className="text-xl font-bold text-white">Managing programm download</h2>
        <p className="text-slate-400 text-xs mt-1">
          Файлы будут сохранены в директорию бэкенда `/g-code/` для последующего чтения имитатором ЧПУ.
          Files is going to be saved to the folder /g-code/ to be read by the simulator
        </p>
      </div>

      <form onSubmit={handleSubmit} className="space-y-5">
        <div>
          <label className="block text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">
            Peak the machine:
          </label>
          <select
            value={selectedMachine}
            onChange={(e) => setSelectedMachine(e.target.value)}
            className="w-full bg-[#0b1329] border border-slate-800 rounded-xl p-3 text-slate-200 text-sm focus:outline-none focus:border-indigo-500 cursor-pointer"
          >
            <option value="">-- Machine --</option>
            {machines.map(m => (
              <option key={m.id} value={m.id}>
                {m.name} ({m.status === 'working' ? 'Working' : m.status === 'error' ? 'Error' : 'Idle'})
              </option>
            ))}
          </select>
        </div>

        <div>
          <label className="block text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">
            Programm file (.nc, .gcode):
          </label>
          <input
            type="file"
            accept=".nc,.gcode"
            onChange={(e) => {
              if (e.target.files && e.target.files[0]) {
                setFile(e.target.files[0]);
              }
            }}
            className="w-full bg-[#0b1329] border border-slate-800 rounded-xl p-3 text-slate-400 text-sm file:mr-4 file:py-1.5 file:px-3 file:rounded-lg file:border-0 file:text-xs file:font-bold file:bg-indigo-600 file:text-white hover:file:bg-indigo-700 file:cursor-pointer"
          />
        </div>

        <button
          type="submit"
          disabled={uploading}
          className="w-full bg-indigo-600 hover:bg-indigo-700 disabled:bg-slate-700 text-white font-bold p-3.5 rounded-xl text-sm transition-all active:scale-[0.99] cursor-pointer shadow-md shadow-indigo-950/50"
        >
          {uploading ? 'Data transfering...' : '🚀 Send the programm'}
        </button>
      </form>
    </div>
  );
}

// frontend/src/components/GcodeUpload.vue
<script setup>
    import { ref } from 'vue'
    import axios from 'axios'

    const raw_file = ref(null)

    const selected_machine_id = ref(1)
    const file_name = ref("")

    const file_input = ref(null)

    const trigger_file_select = () => {
        file_input.value.click()
    }

    const on_file_selected = (event) => {
        const file = event.target.files[0]

        if (file) {
            file_name.value = file.name
            raw_file.value = file
        }
    }

    const upload_gcode = async () => {
      if (!raw_file.value) {
        alert("Please select a G-code file")
        return
      }
      try {
        const form_data = new FormData()

        form_data.append('file', raw_file.value)
        form_data.append('machine_id', selected_machine_id.value)

        await axios.post(`http://127.0.0.1:8000/telemetry/machines/${selected_machine_id.value}/upload-gcode`,
          form_data,
          {
            headers: {
              'Content-Type': 'multipart/form-data'
            }
          }
        )
        alert("Success")

        file_name.value = ''
        raw_file.value = null
      } catch (error) {
        console.log('Error: ', error)
      }
    }
</script>
<template>
    <div class="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-lg">
    <h2 class="text-lg font-bold text-white mb-4">G-code uploading</h2>
    
    <div class="flex flex-col md:flex-row items-end gap-4">
      
      
      <div class="w-full md:w-1/4">
        <label class="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Target Machine ID</label>
        <input 
          v-model="selected_machine_id"
          type="number" 
          min="1"
          class="w-full bg-slate-950 border border-slate-800 rounded-lg px-4 py-2 text-white font-mono focus:outline-none focus:border-blue-500 transition"
        />
      </div>

      <input 
        type="file" 
        ref="file_input"
        class="hidden" 
        @change="on_file_selected"
      />

      <div class="w-full md:w-2/4 cursor-pointer" @click="trigger_file_select">
        <label class="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Selected G-code File</label>
        <div class="bg-slate-950 border border-slate-800 rounded-lg px-4 py-2 text-slate-400 font-mono text-sm truncate">
            <span v-if="file_name === ''" class="text-slate-600">No file selected...</span>
            <span v-else class="text-slate-600">📄 {{ file_name }}</span>
        </div>
      </div>

      <div class="w-full md:w-1/4">
        <button
            @click="upload_gcode"
            class="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-lg transition duration-200 cursor-pointer">
          Upload to Server
        </button>
      </div>

    </div>
  </div>
</template>
